  
export const FETCH_EMPLOYEES_REQUEST = 'FETCH_EMPLOYEES_REQUEST';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE';
export const CREATE_EMPLOYEES_REQUEST = 'CREATE_EMPLOYEES_REQUEST';
export const CREATE_EMPLOYEES_SUCCESS = 'CREATE_EMPLOYEES_SUCCESS';
export const CREATE_EMPLOYEES_FAILURE = 'CREATE_EMPLOYEES_FAILURE';
export const UPDATE_EMPLOYEES_REQUEST = 'UPDATE_EMPLOYEES_REQUEST';
export const UPDATE_EMPLOYEES_SUCCESS = 'UPDATE_EMPLOYEES_SUCCESS';
export const UPDATE_EMPLOYEES_FAILURE = 'UPDATE_EMPLOYEES_FAILURE';
export const DELETE_EMPLOYEES_REQUEST = 'DELETE_EMPLOYEES_REQUEST';
export const DELETE_EMPLOYEES_SUCCESS = 'DELETE_EMPLOYEES_SUCCESS';
export const DELETE_EMPLOYEES_FAILURE = 'DELETE_EMPLOYEES_FAILURE';
export const LOGIN_EMPLOYEE_REQUEST = 'LOGIN_EMPLOYEE_REQUEST';
export const LOGIN_EMPLOYEE_SUCCESS = 'LOGIN_EMPLOYEE_SUCCESS';
export const LOGIN_EMPLOYEE_FAILURE = 'LOGIN_EMPLOYEE_FAILURE';
export const FORGOT_PASSWORD_EMPLOYEE_REQUEST = 'FORGOT_PASSWORD_EMPLOYEE_REQUEST';
export const FORGOT_PASSWORD_EMPLOYEE_SUCCESS = 'FORGOT_PASSWORD_EMPLOYEE_SUCCESS';
export const FORGOT_PASSWORD_EMPLOYEE_FAILURE = 'FORGOT_PASSWORD_EMPLOYEE_FAILURE';



